{
 "title": "Whirlpool Live status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   { "name": "poolId", "query": "label_values(poolId)" }
  ]
 },
 "panels": [
  { "title": "Mix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$poolId mixing since",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "repeat": "poolId",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-whirlpool_mix_start_time_seconds{application=\"$application\",poolId=~\"$poolId\"}",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$poolId mixing since",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-whirlpool_mix_start_time_seconds{application=\"$application\",poolId=~\"$poolId\"}",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$poolId mixing since",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-whirlpool_mix_start_time_seconds{application=\"$application\",poolId=~\"$poolId\"}",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$poolId mixing since",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-whirlpool_mix_start_time_seconds{application=\"$application\",poolId=~\"$poolId\"}",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$poolId mixing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "repeat": "poolId",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "whirlpool_pool_mixing_mustmix{application=\"$application\",poolId=~\"$poolId\"}",
     "legendFormat": "mustMix"
    },
    {
     "expr": "whirlpool_pool_mixing_liquidity{application=\"$application\",poolId=~\"$poolId\"}",
     "legendFormat": "liquidity"
    },
    {
     "expr": "sum(whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\"})",
     "legendFormat": "liquidity queue"
    }
   ]
  },
  {
   "title": "$poolId mixing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "whirlpool_pool_mixing_mustmix{application=\"$application\",poolId=~\"$poolId\"}",
     "legendFormat": "mustMix"
    },
    {
     "expr": "whirlpool_pool_mixing_liquidity{application=\"$application\",poolId=~\"$poolId\"}",
     "legendFormat": "liquidity"
    },
    {
     "expr": "sum(whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\"})",
     "legendFormat": "liquidity queue"
    }
   ]
  },
  {
   "title": "$poolId mixing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "whirlpool_pool_mixing_mustmix{application=\"$application\",poolId=~\"$poolId\"}",
     "legendFormat": "mustMix"
    },
    {
     "expr": "whirlpool_pool_mixing_liquidity{application=\"$application\",poolId=~\"$poolId\"}",
     "legendFormat": "liquidity"
    },
    {
     "expr": "sum(whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\"})",
     "legendFormat": "liquidity queue"
    }
   ]
  },
  {
   "title": "$poolId mixing",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "whirlpool_pool_mixing_mustmix{application=\"$application\",poolId=~\"$poolId\"}",
     "legendFormat": "mustMix"
    },
    {
     "expr": "whirlpool_pool_mixing_liquidity{application=\"$application\",poolId=~\"$poolId\"}",
     "legendFormat": "liquidity"
    },
    {
     "expr": "sum(whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\"})",
     "legendFormat": "liquidity queue"
    }
   ]
  },
  {
   "title": "$poolId mixs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "repeat": "poolId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(whirlpool_mix_fail_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(increase(whirlpool_mix_success_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$poolId mixs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(whirlpool_mix_fail_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(increase(whirlpool_mix_success_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$poolId mixs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(whirlpool_mix_fail_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(increase(whirlpool_mix_success_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$poolId mixs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(whirlpool_mix_fail_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(increase(whirlpool_mix_success_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "success"
    }
   ]
  },
  {
   "title": "$poolId users",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "repeat": "poolId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\"})+sum(whirlpool_pool_mixing_liquidity{application=\"$application\",poolId=~\"$poolId\"})",
     "legendFormat": "liquidities"
    },
    {
     "expr": "sum(whirlpool_pool_queue_mustmix{application=\"$application\",poolId=~\"$poolId\"})+sum(whirlpool_pool_mixing_mustmix{application=\"$application\",poolId=~\"$poolId\"})",
     "legendFormat": "mustMixs"
    }
   ]
  },
  {
   "title": "$poolId users",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\"})+sum(whirlpool_pool_mixing_liquidity{application=\"$application\",poolId=~\"$poolId\"})",
     "legendFormat": "liquidities"
    },
    {
     "expr": "sum(whirlpool_pool_queue_mustmix{application=\"$application\",poolId=~\"$poolId\"})+sum(whirlpool_pool_mixing_mustmix{application=\"$application\",poolId=~\"$poolId\"})",
     "legendFormat": "mustMixs"
    }
   ]
  },
  {
   "title": "$poolId users",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\"})+sum(whirlpool_pool_mixing_liquidity{application=\"$application\",poolId=~\"$poolId\"})",
     "legendFormat": "liquidities"
    },
    {
     "expr": "sum(whirlpool_pool_queue_mustmix{application=\"$application\",poolId=~\"$poolId\"})+sum(whirlpool_pool_mixing_mustmix{application=\"$application\",poolId=~\"$poolId\"})",
     "legendFormat": "mustMixs"
    }
   ]
  },
  {
   "title": "$poolId users",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\"})+sum(whirlpool_pool_mixing_liquidity{application=\"$application\",poolId=~\"$poolId\"})",
     "legendFormat": "liquidities"
    },
    {
     "expr": "sum(whirlpool_pool_queue_mustmix{application=\"$application\",poolId=~\"$poolId\"})+sum(whirlpool_pool_mixing_mustmix{application=\"$application\",poolId=~\"$poolId\"})",
     "legendFormat": "mustMixs"
    }
   ]
  },
  {
   "title": "$poolId abuse",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "repeat": "poolId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(whirlpool_blame_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "blame"
    },
    {
     "expr": "sum(increase(whirlpool_ban_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "ban"
    }
   ]
  },
  {
   "title": "$poolId abuse",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(whirlpool_blame_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "blame"
    },
    {
     "expr": "sum(increase(whirlpool_ban_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "ban"
    }
   ]
  },
  {
   "title": "$poolId abuse",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(whirlpool_blame_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "blame"
    },
    {
     "expr": "sum(increase(whirlpool_ban_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "ban"
    }
   ]
  },
  {
   "title": "$poolId abuse",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(whirlpool_blame_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "blame"
    },
    {
     "expr": "sum(increase(whirlpool_ban_total{application=\"$application\",poolId=~\"$poolId\"}[$__rate_interval]))",
     "legendFormat": "ban"
    }
   ]
  },
  { "title": "Tor usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "$poolId Tor usage (mixs)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "repeat": "poolId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "whirlpool_mix_input_total{application=\"$application\",poolId=~\"$poolId\",tor=\"true\"}",
     "legendFormat": "Tor"
    },
    {
     "expr": "whirlpool_mix_input_total{application=\"$application\",poolId=~\"$poolId\",tor=\"false\"}",
     "legendFormat": "clearnet"
    }
   ]
  },
  {
   "title": "$poolId Tor usage (mixs)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "whirlpool_mix_input_total{application=\"$application\",poolId=~\"$poolId\",tor=\"true\"}",
     "legendFormat": "Tor"
    },
    {
     "expr": "whirlpool_mix_input_total{application=\"$application\",poolId=~\"$poolId\",tor=\"false\"}",
     "legendFormat": "clearnet"
    }
   ]
  },
  {
   "title": "$poolId Tor usage (mixs)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "whirlpool_mix_input_total{application=\"$application\",poolId=~\"$poolId\",tor=\"true\"}",
     "legendFormat": "Tor"
    },
    {
     "expr": "whirlpool_mix_input_total{application=\"$application\",poolId=~\"$poolId\",tor=\"false\"}",
     "legendFormat": "clearnet"
    }
   ]
  },
  {
   "title": "$poolId Tor usage (mixs)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "whirlpool_mix_input_total{application=\"$application\",poolId=~\"$poolId\",tor=\"true\"}",
     "legendFormat": "Tor"
    },
    {
     "expr": "whirlpool_mix_input_total{application=\"$application\",poolId=~\"$poolId\",tor=\"false\"}",
     "legendFormat": "clearnet"
    }
   ]
  },
  {
   "title": "$poolId Tor usage (liquidity queue)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "repeat": "poolId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\",tor=\"true\"}",
     "legendFormat": "Tor"
    },
    {
     "expr": "whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\",tor=\"false\"}",
     "legendFormat": "clearnet"
    }
   ]
  },
  {
   "title": "$poolId Tor usage (liquidity queue)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\",tor=\"true\"}",
     "legendFormat": "Tor"
    },
    {
     "expr": "whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\",tor=\"false\"}",
     "legendFormat": "clearnet"
    }
   ]
  },
  {
   "title": "$poolId Tor usage (liquidity queue)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\",tor=\"true\"}",
     "legendFormat": "Tor"
    },
    {
     "expr": "whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\",tor=\"false\"}",
     "legendFormat": "clearnet"
    }
   ]
  },
  {
   "title": "$poolId Tor usage (liquidity queue)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\",tor=\"true\"}",
     "legendFormat": "Tor"
    },
    {
     "expr": "whirlpool_pool_queue_liquidity{application=\"$application\",poolId=~\"$poolId\",tor=\"false\"}",
     "legendFormat": "clearnet"
    }
   ]
  },
  { "title": "All pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Mixs /day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (poolId)(increase(whirlpool_mix_success_total{application=\"$application\"}[1d]))",
     "legendFormat": "{{poolId}}"
    },
    {
     "expr": "sum (increase(whirlpool_mix_success_total{application=\"$application\"}[1d]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (poolId) (whirlpool_pool_queue_liquidity{application=\"$application\"}) + sum by (poolId)(whirlpool_pool_mixing_liquidity{application=\"$application\"}) + sum by (poolId) (whirlpool_pool_queue_mustmix{application=\"$application\"}) + sum by (poolId)(whirlpool_pool_mixing_mustmix{application=\"$application\"})",
     "legendFormat": "{{poolId}}"
    },
    {
     "expr": "sum(whirlpool_pool_queue_liquidity{application=\"$application\"}) + sum(whirlpool_pool_mixing_liquidity{application=\"$application\"}) + sum(whirlpool_pool_queue_mustmix{application=\"$application\"}) + sum(whirlpool_pool_mixing_mustmix{application=\"$application\"})",
     "legendFormat": "all"
    }
   ]
  }
 ]
}